development:
  mainUrl: http://172.20.10.3:8000
  lcdPort: /dev/tty.usbmodem1423
  micPort: /dev/tty.usbmodem1411
  slack_url: https://hooks.slack.com/services/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
