development:
  mainUrl: http://192.168.0.9:8000
  lcdPort: /dev/tty.usbmodem14313
  micPort: /dev/tty.usbmodem14321
  slack_url: https://hooks.slack.com/services/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
